import Image from 'next/image';
import Header from '@/components/header';
import {EmailForm,EnquiryForm} from '@/components/forms';
const programmes=[
  {title:'Full-Stack Web Development',description:'Explore how websites work, then build a stronger path to the software behind the page.',details:'Learn the foundations of HTML, CSS, JavaScript, databases, and full-stack development through practical projects.'},
  {title:'Network Administration & Security',description:'Develop skills to connect computers, support individuals, and protect digital systems.',details:'Explore computer networks, administration, troubleshooting, and the fundamentals of digital security.'},
  {title:'Data Analytics with Python',description:'Learn how to work with data and turn information into useful insights.',details:'Build skills in Python, data preparation, analysis, and communicating findings through practical exercises.'},
  {title:'AI Engineering',description:'Build the programming and practical AI skills to create useful intelligent applications and agents.',details:'Explore programming foundations, AI applications, and practical projects that solve everyday problems.'}
];
const uses=[['Corporate training','A dedicated space for company workshops, team learning, and professional development.'],['School training sessions','Give your learners practical computer experience and digital skills training.'],['Computer-based testing','Deliver assessments using our ICT facilities and equipment, subject to your technical requirements and any approvals.'],['Certification programmes','Host certification training and preparation. Please discuss any technical or provider requirements.'],['Employee upskilling','Support professional and government employees with digital skills and workplace productivity training.'],['Flexible training arrangements','Discuss one-off sessions, regular training, and suitable schedules for your group’s needs.']];
export default function Home(){return <><Header/><main id="home">
<section className="hero"><div className="wrap hero-grid"><div><span className="eyebrow">Modakeke, Osun State, Nigeria</span><h1>Learn digital skills.<br/><em>Build your<br/>next chapter.</em></h1><p>From your first computer lesson to a career in technology. Learn, practise, and grow at MPIITECH. A training space for learners, schools, and organisations.</p><div className="actions"><a className="button orange" href="#apply">Apply for a programme</a><a className="button outline" href="#programmes">Explore programmes</a></div><small>For students, aspiring professionals, and our community.</small></div><figure className="hero-photo"><Image src="/center.png" alt="MPIITECH training center exterior at sunset" fill priority sizes="(max-width: 700px) 90vw, 470px" unoptimized/><figcaption><strong>A place to learn. A community to grow.</strong><span>Center illustration</span></figcaption></figure></div></section>
<div className="benefits"><div className="wrap"><div><i>⌁</i><p><strong>Practical learning</strong><span>Build skills through doing</span></p></div><div><i>⌘</i><p><strong>Structured training</strong><span>Learn with an instructor</span></p></div><div><i>♧</i><p><strong>Community focused</strong><span>Rooted in Modakeke</span></p></div></div></div>
<section id="programmes" className="section pale"><div className="wrap"><div className="section-heading"><div><span className="eyebrow">Find your starting point</span><h2>A foundation today.<br/>More possibilities tomorrow.</h2></div><p>Start with everyday digital skills, or explore a specialist pathway. Check the application portal for available intakes, fees, and schedules.</p></div>
<article className="foundation card"><div><span className="eyebrow orange-text">Start here · Digital Foundations</span><h3>Get comfortable with computers.</h3><p>Build confidence using a computer for school, work, and everyday life. A practical foundation for secondary school students and beginners.</p><a className="button" href="#apply">Check available programmes</a><EmailForm kind="programme" programme="Digital Foundations"/></div><ol>{['Computer parts, files, and folders','Microsoft Office and productivity tools','Using the internet and staying safe online','An introduction to programming'].map(x=><li key={x}>{x}</li>)}</ol></article>
<div className="programmes-grid">{programmes.map((p,i)=><article className="card programme" key={p.title}><span className="eyebrow orange-text">Pathway / 0{i+1}</span><h3>{p.title}</h3><p>{p.description}</p><details><summary>Explore the skills</summary><p>{p.details}</p></details><EmailForm kind="programme" programme={p.title}/></article>)}</div><p className="section-note">Programmes are introduced as instructors and equipment become available. No application fee is collected on this site.</p></div></section>
<section id="about" className="section"><div className="wrap about-grid"><div><span className="eyebrow">Built around our community</span><h2>Technology skills.<br/>Opportunity close to home.</h2><p>Founded by Modakeke Progressive International (MPI), USA & Canada, MPIITECH brings practical skills and community investment closer to Modakeke and surrounding communities.</p><p>Our focus is simple: give learners the foundations, practice, and support to keep growing.</p><a href="#visit" className="text-link">Learn about MPI</a></div><div className="values-grid">{[['Learn by doing','Hands-on exercises and practical work help turn curiosity into skills.'],['A clear learning journey','Build from basic digital literacy toward more advanced technology skills.'],['Guidance that matters','Learn with instructors who explain, demonstrate, and support your progress.'],['A place to focus','Use dedicated learning spaces at the MPIITECH center in Modakeke.']].map(([title,text])=><div key={title}><h4>{title}</h4><p>{text}</p></div>)}</div></div></section>
<section id="hire" className="section pale"><div className="wrap"><div className="section-heading"><div><span className="eyebrow">A space for your organisation</span><h2>Your training.<br/>Our center.</h2></div><p>Hire the MPIITECH center for organised training, assessments, and workforce development in Modakeke.</p></div><div className="uses-grid">{uses.map(([title,text])=><article className="card" key={title}><h4>{title}</h4><p>{text}</p></article>)}</div><div className="hire-note"><p>Tell us your preferred dates, group size, equipment, and assessment needs. The team will confirm availability, suitability, and pricing.</p><a className="button" href="#enquiry">Enquire about center hire</a></div><div id="enquiry"><EnquiryForm/></div></div></section>
<section id="apply" className="section pale steps-section"><div className="wrap"><span className="eyebrow">Your next step</span><h2>Getting started is straightforward.</h2><div className="steps">{[['Explore your options','Choose the training path that matches your interests and experience.'],['Check the next intake','Visit the application portal for current programme information.'],['Submit your application','Follow the portal instructions and provide your details.']].map(([title,text],i)=><div key={title}><span>{i+1}</span><div><h4>{title}</h4><p>{text}</p></div></div>)}</div><div className="apply-action"><a className="button" href={process.env.NEXT_PUBLIC_PORTAL_URL || '#visit'}>{process.env.NEXT_PUBLIC_PORTAL_URL?'Open application portal':'Contact the center about an intake'}</a></div></div></section>
<section className="section lower"><div className="wrap"><div className="portal" id="portal"><div><span className="eyebrow">Already part of MPIITECH?</span><h2>Your learning, in one place.</h2><p>Access the center portal for learner information, updates, and fees, as well as training and administration tools.</p></div><div><a className="button orange" href={process.env.NEXT_PUBLIC_PORTAL_URL || '#visit'}>{process.env.NEXT_PUBLIC_PORTAL_URL?'Sign in to the portal':'Contact the center'}</a><a className="portal-help" href="#faq">Need assistance?</a></div></div>
<div className="visit-grid" id="visit"><div><span className="eyebrow orange-text">Visit the center</span><h2>Find us in Modakeke.</h2><p>Inside Old Akinola Estate,<br/>opposite Our Lady’s Girls High School,<br/>Modakeke, Osun State, Nigeria.</p><a className="text-link" href="#enquiry">Contact the team</a><span className="contact-separator"> · </span><a className="text-link" href="#about">More about MPIITECH</a></div><div id="faq"><span className="eyebrow">A few useful answers</span>{[['Can I start as a beginner?','Yes. Digital Foundations is designed for beginners and secondary school students. You can request an update when the next intake is available.'],['Where can I find fees and start dates?','Check the application portal for current fees, schedules, and available intakes, or contact the center using the enquiry form.'],['How do I access my existing account?',process.env.NEXT_PUBLIC_PORTAL_URL?'Use the portal sign-in button above to access your existing account.':'Contact the center team for the current learner portal link and help accessing your account.']].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div>
<div className="newsletter"><div><span className="eyebrow">Stay connected</span><h2>What’s next at MPIITECH?</h2><p>Get programme announcements, learning opportunities, and news from the center.</p></div><div><EmailForm kind="newsletter"/><small>Your email is used for the updates you select. Contact the team if you need to stop receiving them.</small></div></div></div></section></main>
<footer><div className="wrap"><span>© {new Date().getFullYear()} MPIITECH · An initiative of MPI, USA & Canada.</span><div><a href="#visit">Modakeke HQ</a><a href="#enquiry">Contact</a><a href="#newsletter-policy">Privacy notice</a></div><details id="newsletter-policy"><summary>Privacy notice</summary><p>Information submitted through this website is emailed to the MPIITECH team through Resend to respond to enquiries or manage requested updates. Newsletter and programme notifications require your consent. Contact the center to withdraw consent or ask about your information.</p></details></div></footer></>}
